name: Kaggle Dataset Update

on:
  push:
    paths:
      - "**.csv"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Kaggle Sync
        env:
          # Kaggle API auth
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          cd Data
          kaggle datasets metadata ${{ vars.KAGGLE_DATASET_PATH}}
          python ../Scripts/kaggleUpload.py
